# Generated by Django 4.2.7 on 2023-11-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='admin_comment',
            field=models.CharField(default='...', max_length=200),
        ),
    ]
